# student_grade = [9.1, 8.8, 7.5]
d = dir(list)
i = dir(float)
r = dir(str)
e = dir(int)
c = dir(__builtins__)
t = dir()

f = open('dir_of_python_items.txt', 'w')
f.write('\n \n \n')
f.write('The following is the print of the contents of List: \n')
f.write(str(d))
f.write('\n \n \n')
f.write('The following is the print of the contents of Float: \n')
f.write(str(i))
f.write('\n \n \n')
f.write('The following is the print of the contents of String: \n')
f.write(str(r))
f.write('\n \n \n')
f.write('The following is the print of the contents of Integers: \n')
f.write(str(e))
f.write('\n \n \n')
f.write('The following is the print of the contents of Built in F(x): \n')
f.write(str(c))
f.close()
